
version: 2
models:
    - name: wa_zip
    - name: pre_wa_zip
      config:
        contract:
          enforced: true
      description: "Washington Zip Codes"
      columns:
        - name: zip_id
          data_type: number(19,0)
          constraints:
            - type: not_null
            - type: unique
              warn_unenforced: false
          tests:
            - unique
        - name: zip
          data_type: varchar
          constraints:
            - type: not_null
            - type: unique
              warn_unenforced: false
          tests:
            - unique
        - name: sourcesystem
          data_type: varchar
        - name: city
          data_type: varchar
        - name: state
          data_type: varchar
